### ISSUE TITLE
How to download your paper

### ISSUE THREAD

**Issue by zq130320339** [RizwanAliQau/tasad#1]
Hello I am very interested in your work, searched and need to pay to download your paper, how can I get the article for free.

**Comment by RizwanAliQau** [comment]
Thank you for your interest. Kindly download the preprint, it includes all the necessary details related to our final version. https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4511136. You can also email me at rizwanaliqau@gmail.com for additional inquiries.
