### ISSUE TITLE
anomaly_source_path

### ISSUE THREAD

**Issue by zq130320339** [RizwanAliQau/tasad#2]
What is the files anomaly_source_path？

**Comment by zq130320339** [comment]
![image](https://github.com/RizwanAliQau/tasad/assets/38161211/1681cca0-411a-4705-a0e0-1b7657988ca2)
是这个纹理图片？

**Comment by RizwanAliQau** [comment]
you can provide any external dataset to insert anomaly, in this paper the anomaly source path is following data: 
    - https://www.robots.ox.ac.uk/~vgg/data/dtd/
